### PR TITLE
Added README and more complex calculations.

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
I improved your awesone calculator application with tkinter, a Python GUI toolkit, by addressing several functional and visual aspects:

1. **Keyboard Event Handling:** Implemented event handling for keyboard inputs (`<Key>` and `<BackSpace>` events) to allow users to interact with the calculator both through keyboard inputs and GUI buttons.

2. **Button Customization:** Styled the calculator buttons based on their functionality:

- Numeric buttons (`0-9`, `.`, `00`) were set with black backgrounds and white text for clarity.
- Operator buttons (`+`, `-`, `*`, `/`, `%`, `=`) were styled with dark gray backgrounds and white text.
- Special function buttons (`CE`, `AC`, `SQRT`, etc.) were given light red backgrounds with white text for clear distinction.
3. **Memory and History Functionality:** Added memory storage (`M+`, `M-`, `MRC`) functionalities to enhance user experience.

4. **Mathematical Operations:** Implemented basic arithmetic operations (`+`, `-`,`*`, `/`), unary operations (`SQRT`, `LOG`, etc.), and memory operations (`M+`, `M-`, `MRC`) to make the calculator functional for everyday calculations.

5. **Error Handling:** Implemented error handling to display user-friendly error messages (Invalid Input) when incorrect input or operations are attempted.

6. **File Handling:** Incorporated file handling (`history.txt`) to persist calculation history across sessions, allowing users to review past calculations.

### CODE REVIEW

**Comment by Filip-Nachov** [comment]
yo thank you for this I actually forgot about this I did it a long time ago and I uploaded it cuz at the time of uploading a was learning git and github so  I wanted to test by uploading a project. Anyways great job I will merge them just let me review the code to make sure every thing is good but by your documentation it looks great

**Review by Filip-Nachov — COMMENTED** [review]
LGTM

**Comment by mgiannopoulos24** [comment]
I'm glad you like it.

**Comment by Filip-Nachov** [comment]
also a question this has been bugging me a bit and it might come of as rude, but why did you contribute to my project and how did you found me. Like I saw your profile and there  are a lot of contributions, but out of all the choices why a basic calculator especially out of all my projects that I am doing, and how did you found me. Also I just want to say I am thankful for your contribution and dont wanna come off as rude  actually I checked the code and the readme its all really good and didnt get the chance to use it so i will rn.

**Comment by mgiannopoulos24** [comment]
No problem. I can explain. I just look for random repositories through Github's advanced search (mostly C and Python) and check them for mistakes. I saw yours and it was interesting. It had no mistakes I just wanted you to have a GUI version of the program.

**Comment by Filip-Nachov** [comment]
interesting? its just a normal console calculator nothing much there are like thousand of those why not something more creative also sorry but am I dumb or what cuz the calculatorGUI aint working for me

**Comment by mgiannopoulos24** [comment]
Do you have tkinter installed?

`pip install tk`

**Comment by Filip-Nachov** [comment]
lol I thought I did and when I tried to the stupid pip wasnt working so I just did `sudo pacman -S tk` and it worked

**Comment by mgiannopoulos24** [comment]
Okay nice. Enjoy 😄

**Comment by Filip-Nachov** [comment]
nice job I like it. Well then ok now it was all fun but I gotta work on my other projects rn check them out. I am currently working on scope (a terminal file manager in python) and Scribe (a vim like text editor in C). They are still in working I am currently doing the Scribe one cuz I had an issue with the scope one so this is like a clearer of my mind

**Comment by mgiannopoulos24** [comment]
Okay. Do you want me to give you ideas to improve them or check them for any mistakes?

**Comment by Filip-Nachov** [comment]
I mean if you want to. its still in the making

**Comment by mgiannopoulos24** [comment]
Alright. I'll see what I can do.

**Pull request merged**
